In [10]:
%matplotlib inline


PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始
---------------

Tensors（张量）

^^^^^^^

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [11]:
from __future__ import print_function
import torch

In [12]:
#创建一个 5x3 矩阵, 但是未初始化:
#不加初始化地构建矩阵，使用torch.empty(row, column)
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8105e-42, 0.0000e+00],
        [0.0000e+00, 1.8567e-01, 0.0000e+00]])


In [13]:
#创建一个随机初始化的矩阵:(row, column)
x = torch.rand(5, 3)
print(x)

tensor([[0.7760, 0.1915, 0.6994],
        [0.5116, 0.1811, 0.9788],
        [0.4263, 0.8539, 0.8947],
        [0.4986, 0.0187, 0.1371],
        [0.6784, 0.6641, 0.1878]])


In [14]:
#创建一个0填充的矩阵，数据类型为long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)



tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [15]:
#创建tensor并使用现有数据初始化:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [17]:
#根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0794, -0.7155, -1.0055],
        [ 1.1701, -0.9484,  1.5951],
        [ 0.1815, -0.9640,  0.6688],
        [-0.1108,  1.3464,  0.4735],
        [ 0.7086, -0.2201,  0.0668]])


In [23]:
#获取 size
#译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍
print(x.size())
#``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.


torch.Size([5, 3])


In [26]:
# 加法操作
y = torch.rand(5, 3)

print ("x")
print (x)
print("y")
print (y)
print("x + y")
print(x + y)

x
tensor([[ 0.0794, -0.7155, -1.0055],
        [ 1.1701, -0.9484,  1.5951],
        [ 0.1815, -0.9640,  0.6688],
        [-0.1108,  1.3464,  0.4735],
        [ 0.7086, -0.2201,  0.0668]])
y
tensor([[0.2891, 0.5321, 0.7848],
        [0.1531, 0.2729, 0.3217],
        [0.9508, 0.9820, 0.5430],
        [0.6174, 0.7694, 0.1152],
        [0.1231, 0.6644, 0.4844]])
x + y
tensor([[ 0.3685, -0.1834, -0.2207],
        [ 1.3231, -0.6755,  1.9168],
        [ 1.1323,  0.0180,  1.2118],
        [ 0.5066,  2.1158,  0.5887],
        [ 0.8317,  0.4443,  0.5512]])


In [28]:
#加法2
print ("x")
print (x)
print("y")
print (y)
print(torch.add(x, y))

x
tensor([[ 0.0794, -0.7155, -1.0055],
        [ 1.1701, -0.9484,  1.5951],
        [ 0.1815, -0.9640,  0.6688],
        [-0.1108,  1.3464,  0.4735],
        [ 0.7086, -0.2201,  0.0668]])
y
tensor([[0.2891, 0.5321, 0.7848],
        [0.1531, 0.2729, 0.3217],
        [0.9508, 0.9820, 0.5430],
        [0.6174, 0.7694, 0.1152],
        [0.1231, 0.6644, 0.4844]])
tensor([[ 0.3685, -0.1834, -0.2207],
        [ 1.3231, -0.6755,  1.9168],
        [ 1.1323,  0.0180,  1.2118],
        [ 0.5066,  2.1158,  0.5887],
        [ 0.8317,  0.4443,  0.5512]])


In [29]:
#提供输出tensor作为参数
print ("x")
print (x)
print("y")
print (y)
result=torch.empty(5,3)
torch.add(x,y,out=result)
print("result")
print(result)

x
tensor([[ 0.0794, -0.7155, -1.0055],
        [ 1.1701, -0.9484,  1.5951],
        [ 0.1815, -0.9640,  0.6688],
        [-0.1108,  1.3464,  0.4735],
        [ 0.7086, -0.2201,  0.0668]])
y
tensor([[0.2891, 0.5321, 0.7848],
        [0.1531, 0.2729, 0.3217],
        [0.9508, 0.9820, 0.5430],
        [0.6174, 0.7694, 0.1152],
        [0.1231, 0.6644, 0.4844]])
result
tensor([[ 0.3685, -0.1834, -0.2207],
        [ 1.3231, -0.6755,  1.9168],
        [ 1.1323,  0.0180,  1.2118],
        [ 0.5066,  2.1158,  0.5887],
        [ 0.8317,  0.4443,  0.5512]])


In [32]:
#替换
# adds x to y
print ("x")
print (x)
print("y")
print (y)
y.add_(x)
print("y")
print(y)
#Note 任何 以``_`` 结尾的操作都会用结果替换原变量. 例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.

x
tensor([[ 0.0794, -0.7155, -1.0055],
        [ 1.1701, -0.9484,  1.5951],
        [ 0.1815, -0.9640,  0.6688],
        [-0.1108,  1.3464,  0.4735],
        [ 0.7086, -0.2201,  0.0668]])
y
tensor([[ 0.4479, -0.8989, -1.2263],
        [ 2.4932, -1.6239,  3.5119],
        [ 1.3137, -0.9460,  1.8807],
        [ 0.3958,  3.4623,  1.0622],
        [ 1.5404,  0.2242,  0.6180]])
y
tensor([[ 5.2734e-01, -1.6145e+00, -2.2318e+00],
        [ 3.6632e+00, -2.5724e+00,  5.1069e+00],
        [ 1.4952e+00, -1.9100e+00,  2.5495e+00],
        [ 2.8495e-01,  4.8087e+00,  1.5357e+00],
        [ 2.2490e+00,  4.0342e-03,  6.8480e-01]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [36]:
#你可以使用与NumPy索引方式相同的操作来进行对张量的操作
print("x")
print(x)
print(x[:, 1]) #第2列
print(x[1, :])  #第2行 
print(x[1, 0:1])  #第1+1行 y索引[0.1)

x
tensor([[ 0.0794, -0.7155, -1.0055],
        [ 1.1701, -0.9484,  1.5951],
        [ 0.1815, -0.9640,  0.6688],
        [-0.1108,  1.3464,  0.4735],
        [ 0.7086, -0.2201,  0.0668]])
tensor([-0.7155, -0.9484, -0.9640,  1.3464, -0.2201])
tensor([ 1.1701, -0.9484,  1.5951])
tensor([1.1701])


In [37]:
# torch.view: 可以改变张量的维度和大小
# 译者注：torch.view 与Numpy的reshape类似
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [38]:
x = torch.randn(1)
print(x)
#如果你有只有一个元素的张量，使用.item()来得到Python数据类型的数值
print(x.item())

tensor([-1.3088])
-1.308803915977478


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [39]:
a = torch.ones(5)
print(a)
aa = torch.ones(5,dtype=torch.long)
print(aa)

tensor([1., 1., 1., 1., 1.])
tensor([1, 1, 1, 1, 1])


In [41]:
b = a.numpy()
print(b)

[2. 2. 2. 2. 2.]


See how the numpy array changed in value.



In [42]:
print(a)
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


 NumPy Array 转化成 Torch Tensor

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

使用from_numpy自动转化



In [44]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)  #默认 dtype=torch.float64
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [45]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改